export type Category = 
  | 'Food'
  | 'Animals'
  | 'Objects'
  | 'Movies'
  | 'Songs'
  | 'Locations'
  | 'Sports'
  | 'Brands'
  | 'Celebrities';

export const CATEGORIES: Category[] = [
  'Food',
  'Animals',
  'Objects',
  'Movies',
  'Songs',
  'Locations',
  'Sports',
  'Brands',
  'Celebrities',
];

export interface WordWithHints {
  word: string;
  hints: string[];
}

export interface WordWithHint {
  word: string;
  hint: string;
}

export const WORD_BANKS: Record<Category, WordWithHints[]> = {
  Food: [
    { word: 'Pizza', hints: ['Round', 'Oven', 'Cheesy', 'Slice'] },
    { word: 'Sushi', hints: ['Rolls', 'Rice', 'Seaweed', 'Chopsticks'] },
    { word: 'Tacos', hints: ['Folded', 'Street', 'Filling', 'Handheld'] },
    { word: 'Burger', hints: ['Stacked', 'Patty', 'Fast', 'Bun'] },
    { word: 'Pasta', hints: ['Noodles', 'Boiled', 'Sauce', 'Twirl'] },
    { word: 'Ice Cream', hints: ['Cold', 'Sweet', 'Creamy', 'Scoop'] },
    { word: 'Chocolate', hints: ['Sweet', 'Brown', 'Cocoa', 'Bar'] },
    { word: 'Apple', hints: ['Fruit', 'Crunchy', 'Tree', 'Lunchbox'] },
    { word: 'Banana', hints: ['Fruit', 'Peel', 'Curved', 'Bunch'] },
    { word: 'Steak', hints: ['Meat', 'Grilled', 'Juicy', 'Cut'] },
    { word: 'Salad', hints: ['Fresh', 'Leaves', 'Bowl', 'Healthy'] },
    { word: 'Soup', hints: ['Hot', 'Liquid', 'Bowl', 'Spoon'] },
    { word: 'Sandwich', hints: ['Bread', 'Layers', 'Portable', 'Lunch'] },
    { word: 'Cake', hints: ['Dessert', 'Layers', 'Frosting', 'Celebration'] },
    { word: 'Cookie', hints: ['Baked', 'Sweet', 'Round', 'Snack'] },
    { word: 'Ramen', hints: ['Broth', 'Noodles', 'Bowl', 'Comfort'] },
    { word: 'Donut', hints: ['Fried', 'Ring', 'Glazed', 'Breakfast'] },
    { word: 'French Fries', hints: ['Potato', 'Crispy', 'Side', 'Salt'] },
    { word: 'Pancakes', hints: ['Breakfast', 'Stack', 'Syrup', 'Flat'] },
    { word: 'Hot Dog', hints: ['Bun', 'Sausage', 'Street', 'Stadium'] },
    { word: 'Cheese', hints: ['Dairy', 'Slices', 'Blocks', 'Aged'] },
    { word: 'Orange', hints: ['Citrus', 'Fruit', 'Juice', 'Peel'] },
    { word: 'Cereal', hints: ['Breakfast', 'Bowl', 'Milk', 'Crunchy'] },
    { word: 'Popcorn', hints: ['Corn', 'Bucket', 'Snack', 'Movie'] },
    { word: 'Noodles', hints: ['Long', 'Boiled', 'Stir-fry', 'Dish'] },
    { word: 'Burrito', hints: ['Wrapped', 'Rice', 'Beans', 'Roll'] },
    { word: 'Fried Chicken', hints: ['Crispy', 'Pieces', 'Bones', 'Bucket'] },
    { word: 'Bagel', hints: ['Round', 'Hole', 'Toasted', 'Spread'] },
    { word: 'Muffin', hints: ['Baked', 'Cup', 'Breakfast', 'Blueberry'] },
    { word: 'Smoothie', hints: ['Blended', 'Fruit', 'Cold', 'Straw'] },
    { word: 'Milkshake', hints: ['Thick', 'Sweet', 'Straw', 'Diner'] },
    { word: 'Sushi Roll', hints: ['Seaweed', 'Rice', 'Small', 'Bites'] },
    { word: 'Dumplings', hints: ['Wrapped', 'Filling', 'Steam', 'Bite-sized'] },
    { word: 'Curry', hints: ['Sauce', 'Spices', 'Rice', 'Aromatic'] },
    { word: 'Lasagna', hints: ['Layers', 'Oven', 'Pasta', 'Rectangular'] },
    { word: 'Guacamole', hints: ['Green', 'Dip', 'Avocado', 'Party'] },
    { word: 'Pudding', hints: ['Soft', 'Dessert', 'Cup', 'Spoon'] },
    { word: 'Brownie', hints: ['Chocolate', 'Square', 'Chewy', 'Pan'] },
    { word: 'Yogurt', hints: ['Dairy', 'Cup', 'Spoon', 'Tart'] },
  ],
  Animals: [
    { word: 'Dog', hints: ['Loyal', 'Pet', 'Tail', 'Walks'] },
    { word: 'Cat', hints: ['Feline', 'Purrs', 'Whiskers', 'Climbs'] },
    { word: 'Elephant', hints: ['Large', 'Gray', 'Herd', 'Wild'] },
    { word: 'Lion', hints: ['Predator', 'Savannah', 'Group', 'Roar'] },
    { word: 'Tiger', hints: ['Striped', 'Hunter', 'Feline', 'Forest'] },
    { word: 'Bear', hints: ['Furry', 'Forest', 'Big', 'Claws'] },
    { word: 'Penguin', hints: ['Black and white', 'Bird', 'Waddles', 'Cold'] },
    { word: 'Dolphin', hints: ['Aquatic', 'Smart', 'Jumps', 'Groups'] },
    { word: 'Eagle', hints: ['Flying', 'Talons', 'Nest', 'Sharp eyes'] },
    { word: 'Shark', hints: ['Ocean', 'Teeth', 'Fin', 'Predator'] },
    { word: 'Monkey', hints: ['Playful', 'Tail', 'Climbs', 'Tree'] },
    { word: 'Zebra', hints: ['Striped', 'Herd', 'Grass', 'Savannah'] },
    { word: 'Giraffe', hints: ['Tall', 'Spots', 'Leaves', 'Savannah'] },
    { word: 'Rabbit', hints: ['Hopping', 'Ears', 'Burrow', 'Fast'] },
    { word: 'Whale', hints: ['Massive', 'Ocean', 'Breathes air', 'Songs'] },
    { word: 'Fox', hints: ['Cunning', 'Orange', 'Tail', 'Nocturnal'] },
    { word: 'Wolf', hints: ['Howl', 'Pack', 'Forest', 'Hunt'] },
    { word: 'Kangaroo', hints: ['Jump', 'Tail', 'Pouch', 'Grassland'] },
    { word: 'Panda', hints: ['Black and white', 'Clumsy', 'Herbivore', 'Bamboo eater'] },
    { word: 'Koala', hints: ['Tree', 'Sleepy', 'Leaves', 'Pouch'] },
    { word: 'Horse', hints: ['Hooves', 'Ride', 'Mane', 'Stable'] },
    { word: 'Cow', hints: ['Farm', 'Milk source', 'Herd', 'Grazes'] },
    { word: 'Chicken', hints: ['Farm', 'Feathers', 'Clucks', 'Eggs'] },
    { word: 'Owl', hints: ['Night', 'Silent', 'Eyes', 'Tree'] },
    { word: 'Snake', hints: ['Slither', 'Scales', 'No legs', 'Hiss'] },
    { word: 'Frog', hints: ['Green', 'Jump', 'Pond', 'Croak'] },
    { word: 'Duck', hints: ['Water', 'Waddle', 'Bill', 'Pond'] },
    { word: 'Squirrel', hints: ['Tree', 'Nuts', 'Tail', 'Quick'] },
    { word: 'Bat', hints: ['Night', 'Wings', 'Cave', 'Upside-down'] },
    { word: 'Deer', hints: ['Forest', 'Graceful', 'Antlers', 'Herbivore'] },
    { word: 'Camel', hints: ['Desert', 'Humps', 'Long distance', 'Sand'] },
    { word: 'Goat', hints: ['Farm', 'Climb', 'Beard', 'Curious'] },
    { word: 'Sheep', hints: ['Flock', 'Wool', 'Farm', 'Soft'] },
    { word: 'Pig', hints: ['Farm', 'Snout', 'Mud', 'Pink'] },
    { word: 'Parrot', hints: ['Colorful', 'Talkative', 'Bird', 'Perch'] },
    { word: 'Seal', hints: ['Flippers', 'Ocean', 'Rocks', 'Calls'] },
    { word: 'Cheetah', hints: ['Fast', 'Spots', 'Chase', 'Savannah'] },
    { word: 'Hippo', hints: ['River', 'Heavy', 'Mouth', 'Territorial'] },
  ],
  Objects: [
    { word: 'Chair', hints: ['Seating', 'Legs', 'Backrest', 'Furniture'] },
    { word: 'Table', hints: ['Flat', 'Surface', 'Dining', 'Furniture'] },
    { word: 'Lamp', hints: ['Light source', 'Shade', 'Switch', 'Corner'] },
    { word: 'Clock', hints: ['Time', 'Hands', 'Wall', 'Tick'] },
    { word: 'Book', hints: ['Pages', 'Reading', 'Cover', 'Story'] },
    { word: 'Phone', hints: ['Screen', 'Pocket', 'Calls', 'Notifications'] },
    { word: 'Camera', hints: ['Lens', 'Photo', 'Click', 'Capture'] },
    { word: 'Guitar', hints: ['Strings', 'Music', 'Strum', 'Instrument'] },
    { word: 'Umbrella', hints: ['Rain', 'Handle', 'Fold', 'Cover'] },
    { word: 'Backpack', hints: ['Straps', 'Zipper', 'Carry', 'School'] },
    { word: 'Glasses', hints: ['Frames', 'Lenses', 'Vision', 'Nose'] },
    { word: 'Wallet', hints: ['Money', 'Cards', 'Pocket', 'Fold'] },
    { word: 'Key', hints: ['Metal', 'Teeth', 'Lock', 'Door'] },
    { word: 'Watch', hints: ['Wrist', 'Time', 'Band', 'Accessory'] },
    { word: 'Mirror', hints: ['Reflection', 'Glass', 'Wall', 'Face'] },
    { word: 'Laptop', hints: ['Portable', 'Keyboard', 'Screen', 'Work'] },
    { word: 'Pen', hints: ['Ink', 'Writing', 'Cap', 'Pocket'] },
    { word: 'Pillow', hints: ['Soft', 'Bed', 'Head', 'Sleep'] },
    { word: 'Blanket', hints: ['Warm', 'Bed', 'Cover', 'Cozy'] },
    { word: 'Headphones', hints: ['Music', 'Ears', 'Cable', 'Listen'] },
    { word: 'Remote', hints: ['Buttons', 'TV', 'Channel', 'Click'] },
    { word: 'Mouse', hints: ['Pointer', 'Click', 'Computer', 'Desk'] },
    { word: 'Keyboard', hints: ['Typing', 'Keys', 'Letters', 'Computer'] },
    { word: 'Microwave', hints: ['Kitchen', 'Heat', 'Timer', 'Door'] },
    { word: 'Toothbrush', hints: ['Bathroom', 'Bristles', 'Mouth', 'Routine'] },
    { word: 'Bottle', hints: ['Container', 'Cap', 'Drink', 'Reusable'] },
    { word: 'Spoon', hints: ['Bowl-shaped', 'Metal', 'Eat', 'Stir'] },
    { word: 'Fork', hints: ['Prongs', 'Metal', 'Eat', 'Table'] },
    { word: 'Plate', hints: ['Round', 'Dish', 'Meal', 'Ceramic'] },
    { word: 'Towel', hints: ['Dry', 'Fabric', 'Bathroom', 'Beach'] },
    { word: 'Door', hints: ['Hinges', 'Handle', 'Open', 'Close'] },
    { word: 'Window', hints: ['Glass', 'Frame', 'View', 'Open'] },
    { word: 'Suitcase', hints: ['Travel', 'Handle', 'Wheels', 'Clothes'] },
    { word: 'Scissors', hints: ['Blades', 'Cut', 'Handle', 'Sharp'] },
    { word: 'Ruler', hints: ['Measure', 'Straight', 'Lines', 'Desk'] },
    { word: 'Fan', hints: ['Blades', 'Air', 'Cool', 'Spin'] },
    { word: 'Trash Can', hints: ['Bin', 'Waste', 'Liner', 'Lid'] },
    { word: 'Notebook', hints: ['Pages', 'Spiral', 'Write', 'School'] },
    { word: 'Desk', hints: ['Work surface', 'Drawers sometimes', 'Office', 'Legs'] },
    { word: 'Sofa', hints: ['Living room', 'Cushions', 'Seats several', 'Relax'] },
    { word: 'Bed', hints: ['Frame', 'Mattress', 'Nighttime', 'Sheets'] },
    { word: 'Television', hints: ['Large screen', 'Living room', 'Episodes', 'Remote partner'] },
    { word: 'Monitor', hints: ['Screen', 'On a stand', 'Desk', 'Cables attached'] },
    { word: 'Speaker', hints: ['Sound', 'Box-shaped', 'Volume', 'Music source'] },
    { word: 'Mug', hints: ['Handle', 'Hot drink', 'Ceramic', 'Desk item'] },
    { word: 'Cup', hints: ['Small container', 'Drink', 'Handle sometimes', 'Stackable'] },
    { word: 'Bowl', hints: ['Curved dish', 'Food container', 'Spoon used', 'No corners'] },
    { word: 'Calendar', hints: ['Dates', 'Months', 'Wall or desk', 'Planning'] },
    { word: 'Journal', hints: ['Blank pages', 'Personal writing', 'Cover', 'Private thoughts'] },
    { word: 'Marker', hints: ['Thick writing tool', 'Cap', 'Ink smell', 'Whiteboard'] },
    { word: 'Highlighter', hints: ['Bright colors', 'Transparent ink', 'Study tool', 'Text emphasis'] },
    { word: 'Eraser', hints: ['Small block', 'Removes marks', 'Stationery', 'Smudges sometimes'] },
    { word: 'Stapler', hints: ['Desk tool', 'Metal pieces', 'Papers together', 'Press down'] },
    { word: 'Tape', hints: ['Transparent strip', 'Adhesive', 'Roll', 'Sticks things'] },
    { word: 'Envelope', hints: ['Paper container', 'Folded flap', 'Mail', 'Addressed'] },
    { word: 'Globe', hints: ['Sphere', 'Countries shown', 'Classroom', 'Spins'] },
    { word: 'Map', hints: ['Flat', 'Locations', 'Folded often', 'Navigation'] },
    { word: 'Calculator', hints: ['Buttons', 'Numbers', 'Small screen', 'Math helper'] },
    { word: 'Game Controller', hints: ['Buttons', 'Joysticks', 'Hands-on', 'Connected to screen'] },
    { word: 'Console', hints: ['Box near TV', 'Games', 'Cables', 'Controllers connect'] },
    { word: 'Flashlight', hints: ['Portable', 'Beam of light', 'Batteries', 'Dark places'] },
    { word: 'Power Bank', hints: ['Portable', 'Charges devices', 'Battery inside', 'Cable needed'] },
    { word: 'Thermos', hints: ['Keeps drinks warm', 'Lid as cup', 'Metal cylinder', 'Travel'] },
    { word: 'Air Conditioner', hints: ['Wall or window unit', 'Cool air', 'Vents', 'Remote sometimes'] },
    { word: 'Heater', hints: ['Warm air', 'Coil or vents', 'Cold days', 'Portable sometimes'] },
    { word: 'Vacuum', hints: ['Floor cleaning', 'Cord or cordless', 'Noise', 'Dust container'] },
    { word: 'Broom', hints: ['Handle', 'Bristles', 'Floor', 'Sweeping'] },
    { word: 'Mop', hints: ['Handle', 'Wet cleaning', 'Bucket partner', 'Floors'] },
    { word: 'Bucket', hints: ['Container', 'Handle', 'Water', 'Cleaning'] },
    { word: 'Laundry Basket', hints: ['Holes in sides', 'Clothes', 'Plastic or fabric', 'Carried to washer'] },
    { word: 'Iron', hints: ['Hot surface', 'Clothes', 'Glides', 'Removes wrinkles'] },
    { word: 'Hairdryer', hints: ['Handle', 'Warm air', 'Bathroom', 'Loud'] },
    { word: 'Comb', hints: ['Teeth', 'Hair', 'Small', 'Often in bag'] },
    { word: 'Razor', hints: ['Blade', 'Handle', 'Bathroom', 'Shaving'] },
    { word: 'Soap', hints: ['Bar or liquid', 'Foam', 'Sink or shower', 'Removes dirt'] },
    { word: 'Curtain', hints: ['Fabric panel', 'Hangs', 'Covers windows', 'Slides'] },
    { word: 'Rug', hints: ['Floor', 'Fabric', 'Soft underfoot', 'Rectangular or circular'] },
    { word: 'Mousepad', hints: ['Flat', 'Soft top', 'Desk', 'Under a small device'] },
    { word: 'Plant Pot', hints: ['Container', 'Soil', 'Holds roots', 'Sits on sill or floor'] },
  ],
  Movies: [
    { word: 'Titanic', hints: ['Ship', 'Cold water', 'Romance', 'Historical setting'] },
    { word: 'Star Wars', hints: ['Space', 'Rebellion', 'Laser weapons', 'Galaxy'] },
    { word: 'The Matrix', hints: ['Reality', 'Glitches', 'Computer world', 'Choice'] },
    { word: 'Inception', hints: ['Dreams', 'Layers', 'Uncertain ending', 'Team mission'] },
    { word: 'Avatar', hints: ['Blue beings', 'Forest world', 'Connection', 'Colonizers'] },
    { word: 'Jurassic Park', hints: ['Dinosaurs', 'Island', 'Theme park', 'Escape'] },
    { word: 'The Lion King', hints: ['Savannah', 'Animals', 'Family', 'Leadership'] },
    { word: 'Frozen', hints: ['Ice', 'Snow', 'Sisters', 'Powers'] },
    { word: 'Toy Story', hints: ['Toys', 'Childhood', 'Jealousy', 'Owner'] },
    { word: 'Harry Potter', hints: ['Magic', 'Boarding school', 'Scar', 'Spells'] },
    { word: 'The Godfather', hints: ['Family business', 'Organized crime', 'Respect', 'Tradition'] },
    { word: 'Pulp Fiction', hints: ['Crime', 'Nonlinear', 'Diner', 'Suit-wearing characters'] },
    { word: 'The Dark Knight', hints: ['Vigilante', 'City', 'Clown villain', 'Chaos'] },
    { word: 'Forrest Gump', hints: ['Running', 'History overlaps', 'Bench', 'Naïve viewpoint'] },
    { word: 'Casablanca', hints: ['Classic', 'War backdrop', 'Bar owner', 'Airport scene'] },
    { word: 'The Avengers', hints: ['Team', 'City battle', 'Different powers', 'Alien threat'] },
    { word: 'Finding Nemo', hints: ['Fish', 'Ocean journey', 'Parent & child', 'Reef'] },
    { word: 'Shrek', hints: ['Ogre', 'Swamp', 'Fairy tale twists', 'Talkative companion'] },
    { word: 'Black Panther', hints: ['Fictional nation', 'Advanced technology', 'Royalty', 'Suit'] },
    { word: 'La La Land', hints: ['Musical', 'City of dreams', 'Jazz', 'Auditions'] },
    { word: 'Spider-Man', hints: ['Wall-climbing', 'Teen hero', 'City', 'Webs'] },
    { word: 'The Incredibles', hints: ['Family', 'Hidden powers', 'Suburban life', 'Matching outfits'] },
    { word: 'Up', hints: ['Balloons', 'Old man', 'Journey', 'Floating home'] },
    { word: 'Inside Out', hints: ['Emotions', 'Inside mind', 'Childhood', 'Headquarters'] },
    { word: 'The Notebook', hints: ['Romance', 'Letters', 'Lake', 'Memory'] },
    { word: 'Gladiator', hints: ['Arena combat', 'Empire', 'Revenge', 'Crowd'] },
    { word: 'The Terminator', hints: ['Robot', 'Future', 'Time travel', 'Relentless'] },
    { word: 'Rocky', hints: ['Boxing', 'Training', 'Underdog', 'Steps'] },
    { word: 'Mean Girls', hints: ['High school', 'Cliques', 'Pink', 'Rumors'] },
    { word: 'The Hunger Games', hints: ['Arena', 'Districts', 'Televised', 'Survival'] },
    { word: 'The Shawshank Redemption', hints: ['Prison', 'Friendship', 'Escape', 'Hope'] },
    { word: 'Interstellar', hints: ['Space travel', 'Time dilation', 'Dusty planet', 'Family'] },
    { word: 'Coco', hints: ['Music', 'Family', 'Ancestor world', 'Holiday'] },
    { word: 'Moana', hints: ['Ocean', 'Voyage', 'Island', 'Guiding star'] },
    { word: 'Jaws', hints: ['Shark', 'Beach town', 'Boat', 'Suspenseful music'] },
    { word: 'Frozen II', hints: ['Sisters', 'Forest', 'Past secrets', 'Voices calling'] },
  ],
  Songs: [
    { word: 'Bohemian Rhapsody', hints: ['Operatic sections', 'Piano', 'Genre-mixing', 'Long track'] },
    { word: 'Stairway to Heaven', hints: ['Gradual build', 'Rock classic', 'Iconic solo', 'Mystical lyrics'] },
    { word: 'Billie Jean', hints: ['Bassline', 'Dance track', 'Accusation theme', 'Pop hit'] },
    { word: 'Hotel California', hints: ['Guitar solo', 'Mysterious place', 'Check-in imagery', 'Desert vibe'] },
    { word: 'Sweet Child O Mine', hints: ['Rock', 'High vocals', 'Famous intro riff', '80s feel'] },
    { word: 'Imagine', hints: ['Piano ballad', 'Idealistic', 'Soft voice', 'Minimal arrangement'] },
    { word: 'Hey Jude', hints: ['Singalong', 'Long outro', 'Comforting tone', 'Piano-driven'] },
    { word: 'Smells Like Teen Spirit', hints: ['Grunge', 'Distorted guitars', 'Mumbled lyrics', 'Youth rebellion'] },
    { word: 'Thunderstruck', hints: ['Chant-like intro', 'Rock anthem', 'Power chords', 'Electric feel'] },
    { word: 'Dancing Queen', hints: ['Disco', 'Celebration', 'Floor filler', 'Seventeen mentioned'] },
    { word: 'Like a Rolling Stone', hints: ['Folk-rock', 'Storytelling', 'Harsh tone', 'Classic track'] },
    { word: 'Purple Rain', hints: ['Slow build', 'Guitar solo', 'Emotional', 'Color in title'] },
    { word: 'Yesterday', hints: ['Short', 'Melancholic', 'Acoustic', 'Nostalgic'] },
    { word: 'We Will Rock You', hints: ['Stomps', 'Claps', 'Chant', 'Arena favorite'] },
    { word: 'Eye of the Tiger', hints: ['Motivational', 'Training montage', 'Rock', 'Challenge'] },
    { word: 'Shape of You', hints: ['Pop', 'Bars imagery', 'Catchy marimba line', 'Danceable'] },
    { word: 'Blinding Lights', hints: ['Synthwave', 'Neon vibe', 'Driving at night', 'Retro sound'] },
    { word: 'Rolling in the Deep', hints: ['Powerful vocal', 'Revenge tone', 'Drums', 'Echoing chorus'] },
    { word: 'Uptown Funk', hints: ['Brass section', 'Funk groove', 'Party track', 'Retro style'] },
    { word: 'Shake It Off', hints: ['Pop', 'Ignoring critics', 'Danceable', 'Cheerful'] },
    { word: 'Thinking Out Loud', hints: ['Slow dance', 'Romantic', 'Wedding favorite', 'Guitar and vocal'] },
    { word: 'Lose Yourself', hints: ['Rap', 'Performance anxiety', 'Opportunity', 'Palms imagery'] },
    { word: 'Stayin Alive', hints: ['Disco', 'Falsetto', 'City strut', 'Bee-like metaphor'] },
    { word: 'Bad Guy', hints: ['Whispery vocal', 'Heavy bass', 'Playful menace', 'Minimalist'] },
    { word: 'Someone Like You', hints: ['Ballad', 'Piano', 'Breakup', 'Farewell tone'] },
    { word: 'All of Me', hints: ['Love song', 'Piano', 'Dedication', 'Wedding usage'] },
    { word: 'Halo', hints: ['Pop ballad', 'Light imagery', 'Guardian feel', 'Soaring chorus'] },
    { word: 'Happy', hints: ['Clapping', 'Optimistic', 'Cartoon video', 'Hat and glasses'] },
    { word: 'Blank Space', hints: ['Satirical', 'Relationships', 'Writing motif', 'Pop'] },
    { word: 'Radioactive', hints: ['Apocalyptic', 'Beats', 'Breathing motif', 'Dark mood'] },
    { word: 'Roar', hints: ['Empowerment', 'Animal metaphor', 'Shouty chorus', 'Jungle visuals'] },
    { word: 'Perfect', hints: ['Romantic', 'Slow tempo', 'Snowy video', 'Dance'] },
    { word: 'Viva la Vida', hints: ['Fallen ruler', 'Bells', 'Painting references', 'Shelf of swords'] },
    { word: 'Believer', hints: ['Pain theme', 'Percussive', 'Chant-like', 'High energy'] },
    { word: 'Shallow', hints: ['Duet', 'Movie tie-in', 'Stage performance', 'Big notes'] },
    { word: 'Bad Romance', hints: ['Pop', 'Dark love', 'Chanting hook', 'Dramatic costumes'] },
    { word: 'Umbrella', hints: ['Rain imagery', 'Supportive lyrics', 'Catchy hook', 'Repetitive syllables'] },
  ],
  Locations: [
    { word: 'Paris', hints: ['Capital', 'River', 'Cafés', 'Famous tower'] },
    { word: 'Tokyo', hints: ['Neon lights', 'Crowded trains', 'High-tech', 'Capital'] },
    { word: 'New York', hints: ['Skyscrapers', 'Yellow cars', 'Parks', 'Busy streets'] },
    { word: 'London', hints: ['Rainy', 'Old buildings', 'River', 'Clock tower'] },
    { word: 'Sydney', hints: ['Harbor', 'Coastal', 'Distinct roofline', 'Southern hemisphere'] },
    { word: 'Dubai', hints: ['Desert city', 'Tall buildings', 'Shopping', 'Man-made islands'] },
    { word: 'Rome', hints: ['Ruins', 'Old arena', 'Fountains', 'Capital'] },
    { word: 'Barcelona', hints: ['Colorful buildings', 'Beach city', 'Unfinished church', 'Spain'] },
    { word: 'Amsterdam', hints: ['Canals', 'Bikes', 'Bridges', 'Flat landscape'] },
    { word: 'Singapore', hints: ['Clean', 'Tiny country', 'Humidity', 'Skyline'] },
    { word: 'Bali', hints: ['Tropical', 'Temples', 'Rice terraces', 'Island'] },
    { word: 'Hawaii', hints: ['Islands', 'Volcanoes', 'Beaches', 'Aloha spirit'] },
    { word: 'Iceland', hints: ['Geysers', 'Glaciers', 'Northern lights', 'Sparse population'] },
    { word: 'Egypt', hints: ['Desert', 'River', 'Ancient structures', 'Camels'] },
    { word: 'Brazil', hints: ['Carnival', 'Rainforest', 'Football culture', 'Huge country'] },
    { word: 'Los Angeles', hints: ['Hillside sign', 'Highways', 'Film industry', 'Beaches'] },
    { word: 'San Francisco', hints: ['Hilly', 'Fog', 'Iconic bridge', 'Cable cars'] },
    { word: 'Toronto', hints: ['Tall tower', 'Lakeside', 'Cold winters', 'Canada'] },
    { word: 'Seoul', hints: ['Capital', 'Pop music scene', 'High-tech', 'Crowded city'] },
    { word: 'Hong Kong', hints: ['Harbor', 'Densely built', 'High-rises', 'Night skyline'] },
    { word: 'Bangkok', hints: ['Street food', 'Temples', 'Hot climate', 'Traffic'] },
    { word: 'Las Vegas', hints: ['Casinos', 'Lights', 'Desert', 'All-night'] },
    { word: 'Berlin', hints: ['Capital', 'History', 'Wall remains', 'Nightlife'] },
    { word: 'Moscow', hints: ['Colorful domes', 'Cold', 'Large city', 'Capital'] },
    { word: 'Venice', hints: ['Boats instead of cars', 'Canals', 'Bridges', 'Italy'] },
    { word: 'Chicago', hints: ['Windy', 'Lakefront', 'Tall buildings', 'Deep-dish'] },
    { word: 'Miami', hints: ['Beaches', 'Pastel buildings', 'Humid', 'Nightlife'] },
    { word: 'Athens', hints: ['Ancient ruins', 'Hilltop temple', 'Mediterranean', 'Capital'] },
    { word: 'Madrid', hints: ['Plazas', 'Late dinners', 'Football culture', 'Capital'] },
    { word: 'Cairo', hints: ['Crowded', 'Near desert', 'Historic', 'River'] },
    { word: 'Rio de Janeiro', hints: ['Beaches', 'Huge statue', 'Hills', 'Carnival'] },
    { word: 'Munich', hints: ['Beer festival', 'Germany', 'Traditional clothes', 'City'] },
    { word: 'Jerusalem', hints: ['Old stone city', 'Religious sites', 'Walls', 'Hill'] },
    { word: 'Vienna', hints: ['Classical music', 'Palaces', 'Coffeehouses', 'Central Europe'] },
    { word: 'Zurich', hints: ['Lake', 'Banks', 'Clean', 'Switzerland'] },
    { word: 'Osaka', hints: ['Food scene', 'Castle', 'Neon district', 'Japan'] },
    { word: 'Beijing', hints: ['Capital', 'Squares', 'Historic palaces', 'Crowded'] },
  ],
  Sports: [
    { word: 'Football', hints: ['Team', 'Oval ball', 'End zones', 'Tackles'] },
    { word: 'Basketball', hints: ['Court', 'Dribble', 'Hoop', 'Five a side'] },
    { word: 'Soccer', hints: ['Pitch', 'Goals', 'No hands', 'World tournaments'] },
    { word: 'Tennis', hints: ['Racket', 'Net', 'Singles or doubles', 'Serve'] },
    { word: 'Baseball', hints: ['Diamond', 'Bat', 'Glove', 'Innings'] },
    { word: 'Golf', hints: ['Clubs', 'Green', 'Holes', 'Walks'] },
    { word: 'Swimming', hints: ['Lanes', 'Goggles', 'Pool', 'Strokes'] },
    { word: 'Boxing', hints: ['Ring', 'Gloves', 'Rounds', 'Punches'] },
    { word: 'Cycling', hints: ['Bike', 'Helmet', 'Road', 'Peloton'] },
    { word: 'Running', hints: ['Shoes', 'Track', 'Distance', 'Pace'] },
    { word: 'Volleyball', hints: ['Net', 'Serve', 'Spike', 'Six players'] },
    { word: 'Hockey', hints: ['Stick', 'Goal', 'Fast-paced', 'Protective gear'] },
    { word: 'Cricket', hints: ['Bat', 'Pitch', 'Wickets', 'Overs'] },
    { word: 'Rugby', hints: ['Scrums', 'Tackles', 'Oval ball', 'Physical'] },
    { word: 'Skateboarding', hints: ['Deck', 'Tricks', 'Wheels', 'Ramps'] },
    { word: 'Surfing', hints: ['Board', 'Waves', 'Balance', 'Ocean'] },
    { word: 'Snowboarding', hints: ['Board', 'Snow', 'Slope', 'Bindings'] },
    { word: 'Skiing', hints: ['Poles', 'Snow', 'Downhill', 'Goggles'] },
    { word: 'Badminton', hints: ['Racket', 'Feathered object', 'Net', 'Indoor'] },
    { word: 'Table Tennis', hints: ['Small table', 'Paddles', 'Fast', 'Light ball'] },
    { word: 'Karate', hints: ['Gi', 'Belts', 'Strikes', 'Dojo'] },
    { word: 'Wrestling', hints: ['Mat', 'Grappling', 'Holds', 'Pins'] },
    { word: 'Gymnastics', hints: ['Flips', 'Beam', 'Bars', 'Flexibility'] },
    { word: 'Rowing', hints: ['Boat', 'Oars', 'Crew', 'Synchrony'] },
    { word: 'Archery', hints: ['Bow', 'Arrow', 'Target', 'Accuracy'] },
    { word: 'Fencing', hints: ['Sword', 'Mask', 'Touches', 'Strip'] },
    { word: 'Lacrosse', hints: ['Stick with net', 'Helmet', 'Field', 'Goals'] },
    { word: 'Softball', hints: ['Diamond', 'Underhand pitch', 'Bat', 'Glove'] },
    { word: 'Handball', hints: ['Indoor', 'Throwing', 'Goalkeeper', 'Fast-paced'] },
    { word: 'Water Polo', hints: ['Pool', 'Caps', 'Ball', 'Goals'] },
    { word: 'Figure Skating', hints: ['Ice', 'Music', 'Spins', 'Costumes'] },
    { word: 'Diving', hints: ['Platform', 'Water', 'Twists', 'Splash'] },
    { word: 'Bobsled', hints: ['Ice track', 'Team', 'Sled', 'Speed'] },
    { word: 'Triathlon', hints: ['Swim', 'Bike', 'Run', 'Endurance'] },
    { word: 'Equestrian', hints: ['Horse', 'Jumps', 'Rider', 'Show'] },
    { word: 'Mixed Martial Arts', hints: ['Cage', 'Strikes', 'Submissions', 'Rounds'] },
    { word: 'Esports', hints: ['Digital', 'Teams', 'Spectators', 'Matches'] },
  ],
  Brands: [
    { word: 'Apple', hints: ['Tech company', 'Minimalist design', 'Fruits logo', 'Flagship phones'] },
    { word: 'Nike', hints: ['Sportswear', 'Athletes', 'Simple check mark', 'Motivational slogan'] },
    { word: 'Coca Cola', hints: ['Soft drink', 'Red branding', 'Classic bottle', 'Carbonated'] },
    { word: 'Google', hints: ['Search engine', 'Colorful letters', 'Online tools', 'Maps'] },
    { word: 'Amazon', hints: ['Packages', 'Arrow logo', 'Online marketplace', 'Fast shipping'] },
    { word: 'McDonald\'s', hints: ['Fast food', 'Arches', 'Drive-thru', 'Famous fries'] },
    { word: 'Starbucks', hints: ['Coffee chain', 'Green logo', 'Cups with names', 'Cafe vibe'] },
    { word: 'Tesla', hints: ['Electric cars', 'Charging stations', 'Autopilot', 'Futuristic dashboards'] },
    { word: 'Microsoft', hints: ['Operating system', 'Office software', 'Four colors', 'Tech giant'] },
    { word: 'Disney', hints: ['Theme parks', 'Animated films', 'Castle intro', 'Mouse mascot'] },
    { word: 'Adidas', hints: ['Sportswear', 'Three lines', 'Sneakers', 'Jerseys'] },
    { word: 'Samsung', hints: ['Electronics', 'Phones', 'Screens', 'Korean company'] },
    { word: 'BMW', hints: ['Cars', 'Round badge', 'Luxury', 'German'] },
    { word: 'Netflix', hints: ['Streaming', 'Binge-watching', 'Red interface', 'Original shows'] },
    { word: 'Spotify', hints: ['Music streaming', 'Playlists', 'Green icon', 'Discover Weekly'] },
    { word: 'Pepsi', hints: ['Soft drink', 'Red white blue circle', 'Competes with another cola', 'Carbonated'] },
    { word: 'Toyota', hints: ['Reliable cars', 'Sedans and SUVs', 'Japanese brand', 'Hybrid models'] },
    { word: 'Ford', hints: ['Trucks', 'Oval logo', 'American automaker', 'Long history'] },
    { word: 'Gucci', hints: ['Luxury', 'Fashion house', 'Designer bags', 'Double-letter logo'] },
    { word: 'Louis Vuitton', hints: ['Monogram pattern', 'Brown bags', 'Luxury luggage', 'French fashion'] },
    { word: 'Facebook', hints: ['Social network', 'Blue interface', 'Friends list', 'Timeline'] },
    { word: 'YouTube', hints: ['Videos', 'Play button logo', 'Creators', 'Subscriptions'] },
    { word: 'Uber', hints: ['Ride-hailing', 'App-based', 'Drivers', 'Map view'] },
    { word: 'Airbnb', hints: ['Travel stays', 'Homes instead of hotels', 'Hosts', 'Online booking'] },
    { word: 'Intel', hints: ['Computer chips', 'Processors', 'Inside sticker', 'Tech'] },
    { word: 'Sony', hints: ['Electronics', 'Consoles', 'Audio gear', 'Japanese company'] },
    { word: 'Honda', hints: ['Cars and bikes', 'H logo', 'Reliable', 'Engines'] },
    { word: 'KFC', hints: ['Fried chicken', 'Bucket meals', 'Portrait logo', 'Fast food'] },
    { word: 'Burger King', hints: ['Fast food', 'Crown motif', 'Sandwiches', 'Whopper item'] },
    { word: 'IKEA', hints: ['Furniture', 'Flat boxes', 'DIY assembly', 'Blue and yellow'] },
    { word: 'H&M', hints: ['Clothing chain', 'Affordable fashion', 'Red letters', 'Mall stores'] },
    { word: 'Zara', hints: ['Clothing', 'Fast fashion', 'Neutral logo', 'Trendy'] },
    { word: 'Puma', hints: ['Sportswear', 'Cat silhouette', 'Shoes', 'Athletic gear'] },
    { word: 'Reebok', hints: ['Sneakers', 'Sports brand', 'Gym clothing', 'Logos changed over years'] },
    { word: 'Lego', hints: ['Plastic bricks', 'Building toys', 'Colorful pieces', 'Childhood creativity'] },
    { word: 'Nintendo', hints: ['Game company', 'Family consoles', 'Iconic plumber character', 'Portable handhelds'] },
    { word: 'PlayStation', hints: ['Console brand', 'Controllers', 'Exclusive games', 'Sony'] },
  ],
  Celebrities: [
    { word: 'Leonardo DiCaprio', hints: ['Actor', 'Long career', 'Known for intense roles', 'Environmental advocate'] },
    { word: 'Beyoncé', hints: ['Performer', 'Powerful voice', 'Large-stage shows', 'Global icon'] },
    { word: 'Taylor Swift', hints: ['Songwriter', 'Storytelling lyrics', 'Massive tours', 'Re-recorded work'] },
    { word: 'Tom Hanks', hints: ['Actor', 'Warm screen presence', 'Often plays kind characters', 'Many decades active'] },
    { word: 'Oprah Winfrey', hints: ['Talk show background', 'Media empire', 'Book club influence', 'Philanthropist'] },
    { word: 'Brad Pitt', hints: ['Actor', 'Often in tabloids', 'Leading man', 'Award-winning'] },
    { word: 'Emma Watson', hints: ['Actress', 'British', 'Grew up on a film set', 'UN-related activism'] },
    { word: 'Will Smith', hints: ['Actor', 'Comedy and action roles', 'Music background', 'Family in entertainment'] },
    { word: 'Jennifer Lawrence', hints: ['Actress', 'Archery-related franchise', 'Awards', 'Playful interviews'] },
    { word: 'Chris Hemsworth', hints: ['Actor', 'Associated with a hammer-wielding hero', 'Australian', 'Action roles'] },
    { word: 'Adele', hints: ['Singer', 'Ballads', 'British accent', 'Powerful live performances'] },
    { word: 'Ryan Reynolds', hints: ['Actor', 'Sarcastic humor', 'Fourth-wall-breaking hero role', 'Married to another star'] },
    { word: 'Meryl Streep', hints: ['Actress', 'Many nominations', 'Versatile roles', 'Respected veteran'] },
    { word: 'Dwayne Johnson', hints: ['Former athlete entertainer', 'Muscular build', 'Action movies', 'Eyebrow raise'] },
    { word: 'Selena Gomez', hints: ['Singer and actress', 'Child-star roots', 'Streaming-era music', 'Cosmetics brand'] },
    { word: 'Justin Bieber', hints: ['Singer', 'Discovered young online', 'From Canada', 'Pop career since teen years'] },
    { word: 'Rihanna', hints: ['Singer', 'Island origins', 'Fashion and beauty empire', 'Halftime performer'] },
    { word: 'Drake', hints: ['Rapper', 'Canadian city connection', 'Basketball sidelines', 'Hooks-heavy songs'] },
    { word: 'Ed Sheeran', hints: ['Singer-songwriter', 'Guitar-focused', 'Red hair', 'Loop pedal performances'] },
    { word: 'Ariana Grande', hints: ['Pop singer', 'High notes', 'Signature hairstyle', 'Started on TV'] },
    { word: 'Harry Styles', hints: ['Singer', 'Boy-band history', 'Colorful fashion', 'Solo success'] },
    { word: 'Elon Musk', hints: ['Business figure', 'Space projects', 'Electric cars', 'Online presence'] },
    { word: 'Kim Kardashian', hints: ['Reality TV', 'Business ventures', 'Family-famous', 'Social media presence'] },
    { word: 'Kylie Jenner', hints: ['Cosmetics brand', 'Reality TV family', 'Influencer', 'Entrepreneur'] },
    { word: 'Kanye West', hints: ['Rapper', 'Producer', 'Fashion designer', 'Controversial moments'] },
    { word: 'Billie Eilish', hints: ['Singer', 'Soft vocal style', 'Oversized clothes', 'Dark aesthetics'] },
    { word: 'Shawn Mendes', hints: ['Singer', 'Guitar on stage', 'From Canada', 'Pop ballads'] },
    { word: 'Zendaya', hints: ['Actress', 'Started young on TV', 'High-fashion red carpets', 'Leading roles in teen drama'] },
    { word: 'Robert Downey Jr.', hints: ['Actor', 'Famous armored hero', 'Career comeback', 'Goatee often'] },
    { word: 'Scarlett Johansson', hints: ['Actress', 'Action roles', 'Independent films too', 'Distinct voice'] },
    { word: 'Chris Evans', hints: ['Actor', 'Played a patriotic hero', 'Ensemble films', 'Beard/no beard discourse'] },
    { word: 'Bruno Mars', hints: ['Singer', 'Retro sound', 'High-energy performances', 'Short stature'] },
    { word: 'Lady Gaga', hints: ['Pop star', 'Theatrical outfits', 'Powerful vocals', 'Acting roles too'] },
    { word: 'Post Malone', hints: ['Face tattoos', 'Singer-rapper mix', 'Genre-blending', 'Laid-back image'] },
    { word: 'Miley Cyrus', hints: ['Singer', 'Former child star', 'Raspy voice', 'Reinventions of image'] },
    { word: 'Morgan Freeman', hints: ['Actor', 'Recognizable narration', 'Calm presence', 'Often plays wise characters'] },
    { word: 'Keanu Reeves', hints: ['Actor', 'Action movies', 'Stoic characters', 'Beloved online for kindness'] },
  ],
};

/**
 * Gets the category for a given word
 */
export function getCategoryForWord(word: string): Category | null {
  for (const [category, words] of Object.entries(WORD_BANKS)) {
    if (words.some(w => w.word === word)) {
      return category as Category;
    }
  }
  return null;
}

/**
 * Gets a random hint for a given word (selects one from available hints)
 */
export function getHintForWord(word: string): string | null {
  for (const words of Object.values(WORD_BANKS)) {
    const wordData = words.find(w => w.word === word);
    if (wordData && wordData.hints.length > 0) {
      const randomIndex = Math.floor(Math.random() * wordData.hints.length);
      return wordData.hints[randomIndex];
    }
  }
  return null;
}

/**
 * Selects a random word from the selected categories and randomly selects one hint for it
 */
export function selectRandomWord(selectedCategories: Category[]): WordWithHint {
  if (selectedCategories.length === 0) {
    throw new Error('At least one category must be selected');
  }

  const allWords: WordWithHints[] = [];
  for (const category of selectedCategories) {
    allWords.push(...WORD_BANKS[category]);
  }

  const randomIndex = Math.floor(Math.random() * allWords.length);
  const selectedWordData = allWords[randomIndex];

  const hintIndex = Math.floor(Math.random() * selectedWordData.hints.length);
  const selectedHint = selectedWordData.hints[hintIndex];

  return {
    word: selectedWordData.word,
    hint: selectedHint,
  };
}
